### PR TITLE
Building

### PR DESCRIPTION
**Pull request by dobbim**
Building class is tested with 100% coverage, all test cases passed

### CODE REVIEW

**Comment by aferritto** [comment]
Haven't ran the code but the only things I could see that we may want to change are a couple of the Java docs say '/** Returns' instead of '/** @returns' and giving each getter its own unit test instead of grouping them together.

**Comment by dobbim** [comment]
According to section 7.2 of the google java style guide at (https://google.github.io/styleguide/javaguide.html#s7-javadoc), the correct way to write a single-line Javadoc for a return statement is indeed to write "/** Returns [...] \*/" rather than "/** @return [...] \*/".  If we would like to change that, please specify so in the changes document on Google drive.  Also, the correct Javadoc for a return statement is "@return", not "@returns".

The getter tests can and will be split.

**Comment by aferritto** [comment]
I could go either way but am leaning towards changing it.  What do @jfucci, @zyteka, and @dang32 think?

**Comment by dang32** [comment]
I actually like the Javadoc style where it's "Returns" and not "@return" because it's just a single-line comment, but I don't particularly care.

**Comment by aferritto** [comment]
Ok then.  LGTM.

**Pull request merged**
