### PR TITLE
UI for Paths Between Buildings

### PR DESCRIPTION
**Pull request by jfucci**
Full code for stakeholder review 1. The user can select two buildings, activate the button, and a campus map with the path between the buildings pops up.

### CODE REVIEW

**Comment by aferritto** [comment]
Functionality works for me.  My main suggestions are alphabetizing the list of buildings and maybe adding arrows to the lines to indicate direction

**Comment by aferritto** [comment]
Could also maybe add map pins saying something like "origin" and "destination"

**Comment by aferritto** [comment]
Also getting NullPointerExceptions in CampusTest now

**Comment by dang32** [comment]
Did you change the absolute file paths?

**Comment by aferritto** [comment]
No.  Also at some point we may want do something to handle source == destination.

**Comment by dang32** [comment]
Also my list of buildings is already alphabetized @ferria?

**Pull request merged**
